Adding code guru profiler & cloud9 environment preparation script
aws-samples/amazon-kinesis-analytics-beam-taxi-consumer pull request #9
Opened 2021-07-27 00:42 UTC by minimalistinnovator

*Issue #, if available: https://app.asana.com/0/1200629911302188/1200629911302191, https://app.asana.com/0/1200629911302188/1200654426892291*

*Description of changes:* Added Code Guru Profiler integration for performance analysis (optional). Added cloud9 environment configuration script.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-07-27 11:23 UTC, sthm requested changes

2021-07-27 11:23 UTC, sthm commented on src/main/java/com/amazonaws/samples/beam/taxi/count/TaxiCount.java
> +    if (!StringUtils.isNullOrEmpty(options.getCodeGuruProfilingGroupName())) {
This looks like it's only executed in the main method and hence only monitors the job manager. Can you please ensure that it's also executed on the job managers, eg, by adding a static method to the DoFns that initializes the profiler.

2021-07-27 11:23 UTC, sthm commented on src/main/java/com/amazonaws/samples/beam/taxi/count/TaxiCount.java
> +                        @ProcessElement
A static method or an overwriting the open method (if it exists) could potentially be used to initialize the profiler.

2021-07-28 00:54 UTC, closed without merging

2021-07-28 00:54 UTC, minimalistinnovator commented
Creating a new one to accomodate feedback